[Websocket]
ListenHost = "0.0.0.0"
ListenPort = 3000
Multicore = true

[Router]
Address = "192.168.0.105:4000"


[Consul]
Address = "192.168.0.105:8500"

[Rpc]
ListenHost = "192.168.0.105"
ListenPort = 4001
