[Rpc]
ListenHost = "192.168.0.105"
ListenPort = 4002

[Database]
Host = "192.168.0.105"
Port = 3306
User = "root"
Password = "my-secret-pw"
Database = "xiaogongqiu"

[Redis]
Addr = "192.168.0.105:6379"
Password = ""

[Consul]
Address = "192.168.0.105:8500"

[Kafka]
Addresses = "192.168.0.105:9092"
MsgTopic = "im-msg"
MsgTopicGroup = "im-msg-group-1000"
MsgPartitionCount = 1